# Generated by Django 3.2.3 on 2021-05-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Category_Model',
        ),
        migrations.AddField(
            model_name='gif',
            name='category',
            field=models.ManyToManyField(to='gifs.Category'),
        ),
    ]
